In [1]:
import pandas as pd
df = pd.read_csv(r"E:\Sindhura\DataSets\car_price_prediction.csv",na_values=["-","NA",""],keep_default_na=False)
df.head()

,ID,Price,Levy,Manufacturer,Model,Prod. year,Category,Leather interior,Fuel type,Engine volume,Mileage,Cylinders,Gear box type,Drive wheels,Doors,Wheel,Color,Airbags
0,45654403,13328,1399.0,LEXUS,RX 450,2010,Jeep,Yes,Hybrid,3.5,186005 km,6.0,Automatic,4x4,04-May,Left wheel,Silver,12
1,44731507,16621,1018.0,CHEVROLET,Equinox,2011,Jeep,No,Petrol,3,192000 km,6.0,Tiptronic,4x4,04-May,Left wheel,Black,8
2,45774419,8467,NaN,HONDA,FIT,2006,Hatchback,No,Petrol,1.3,200000 km,4.0,Variator,Front,04-May,Right-hand drive,Black,2
3,45769185,3607,862.0,FORD,Escape,2011,Jeep,Yes,Hybrid,2.5,168966 km,4.0,Automatic,4x4,04-May,Left wheel,White,0
4,45809263,11726,446.0,HONDA,FIT,2014,Hatchback,Yes,Petrol,1.3,91901 km,4.0,Automatic,Front,04-May,Left wheel,Silver,4

In [2]:
len(df)

19237

In [3]:
df.shape

(19237, 18)

In [4]:
def fetch_km(data):
    x=data.split()
    return x[0]

In [5]:
df['Mileage']=df['Mileage'].apply(fetch_km).astype(int)
df['Mileage']

0        186005
1        192000
2        200000
3        168966
4         91901
          ...
19232    300000
19233    161600
19234    116365
19235     51258
19236    186923
Name: Mileage, Length: 19237, dtype: int64

In [6]:
df.dtypes

ID                    int64
Price                 int64
Levy                float64
Manufacturer         object
Model                object
Prod. year            int64
Category             object
Leather interior     object
Fuel type            object
Engine volume        object
Mileage               int64
Cylinders           float64
Gear box type        object
Drive wheels         object
Doors                object
Wheel                object
Color                object
Airbags               int64
dtype: object

In [7]:
df['Levy'] = df['Levy'].fillna(0).astype(int)

## Outlier handling

In [8]:
cat = list(df.select_dtypes(include='object').columns) 
con = list(df.select_dtypes(include='number').columns)

In [9]:
import numpy as np
out_summary = {}
for col in con:

    q1 = np.percentile(df[col], 25)
    q3 = np.percentile(df[col], 75)

    iqr = q3 - q1 

    minimun = q1 - 1.5 * iqr
    maximum = q3 + 1.5 * iqr

    lower_out = df[col] < minimun
    upper_out = df[col] > maximum

    outliers = df[lower_out | upper_out]

    print("=================")
    print(f"Outliers less than minimum: {df[lower_out]}")
    print(f"Outliers more than maximum: {df[upper_out]}")
    print(f"number of outliers for {col}: {len(outliers)}")
    out_summary[col] = {
        "lower": minimun,
        "upper": maximum,
        "outlier_count": len(outliers),
        "outlier_pct": round(len(outliers)/len(df) * 100, 2)
    }

out_report = pd.DataFrame(out_summary).T
out_report

=================
Outliers less than minimum:              ID  Price  Levy   Manufacturer           Model  Prod. year  \
1      44731507  16621  1018      CHEVROLET         Equinox        2011
15     45465200    549  1079         TOYOTA             CHR        2018
21     45168471  20698   586         TOYOTA           Prius        2012
30     44944581  15681  1288  MERCEDES-BENZ            Vito        2007
34     45542380  24462     0           JEEP  Grand Cherokee        2007
...         ...    ...   ...            ...             ...         ...
19176  45511664  14113   531        HYUNDAI        Veloster        2012
19192  45172859  14113     0          SCION              xD        2010
19208  45433278  34811   779         TOYOTA           RAV 4        2013
19223  44571028   8781     0          DODGE         Caliber        2008
19229  39977395     50     0         TOYOTA           Prius        2008

          Category Leather interior       Fuel type Engine volume  Mileage  \
1             Jeep               No          Petrol             3   192000
15            Jeep              Yes          Petrol             2    74146
21           Sedan              Yes  Plug-in Hybrid           1.8   187000
30     Goods wagon               No          Diesel     2.0 Turbo   180000
34            Jeep              Yes          Diesel     3.0 Turbo   250000
...            ...              ...             ...           ...      ...
19176    Hatchback               No          Petrol           1.6   130000
19192    Hatchback               No          Petrol           1.8   203000
19208         Jeep               No          Petrol           2.5   121400
19223    Hatchback               No          Petrol           2.4        0
19229    Hatchback               No          Hybrid           1.5   150000

       Cylinders Gear box type Drive wheels   Doors       Wheel   Color  \
1            6.0     Tiptronic          4x4  04-May  Left wheel   Black
15           4.0     Automatic        Front  04-May  Left wheel   White
21           4.0     Automatic        Front  04-May  Left wheel   White
30           6.0        Manual         Rear  04-May  Left wheel   White
34           6.0     Tiptronic          4x4  04-May  Left wheel   Black
...          ...           ...          ...     ...         ...     ...
19176        4.0        Manual        Front  04-May  Left wheel    Blue
19192        4.0     Automatic        Front  04-May  Left wheel   White
19208        4.0     Tiptronic        Front  04-May  Left wheel    Grey
19223        4.0     Automatic        Front  04-May  Left wheel    Blue
19229        4.0     Automatic        Front  04-May  Left wheel  Silver

       Airbags
1            8
15          12
21          12
30           4
34          10
...        ...
19176       12
19192        8
19208        6
19223        4
19229        6

[2531 rows x 18 columns]
Outliers more than maximum: Empty DataFrame
Columns: [ID, Price, Levy, Manufacturer, Model, Prod. year, Category, Leather interior, Fuel type, Engine volume, Mileage, Cylinders, Gear box type, Drive wheels, Doors, Wheel, Color, Airbags]
Index: []
number of outliers for ID: 2531
=================
Outliers less than minimum: Empty DataFrame
Columns: [ID, Price, Levy, Manufacturer, Model, Prod. year, Category, Leather interior, Fuel type, Engine volume, Mileage, Cylinders, Gear box type, Drive wheels, Doors, Wheel, Color, Airbags]
Index: []
Outliers more than maximum:              ID  Price  Levy   Manufacturer           Model  Prod. year  \
14     45732604  59464   891        HYUNDAI        Santa FE        2016
36     45369569  51746  1077         TOYOTA     CHR Limited        2019
47     45732544  55390  1017        HYUNDAI        Santa FE        2017
56     44316016  87112     0  MERCEDES-BENZ         GLA 250        2019
73     45732043  53154   891        HYUNDAI        Santa FE        2016
...         ...    ...   ...            ...             ...         ...
19144  45733642  56814  1017        HYUNDAI          Sonata        2017
19161  45677230  64290     0          LEXUS  RX 450 F SPORT        2012
19180  45803164  63886  1076        HYUNDAI          Sonata        2020
19188  45571892  61154   579         TOYOTA           RAV 4        2017
19211  45802856  50037   891        HYUNDAI        Santa FE        2016

      Category Leather interior Fuel type Engine volume  Mileage  Cylinders  \
14        Jeep              Yes    Diesel             2    76000        4.0
36        Jeep               No    Petrol             2    10200        4.0
47        Jeep              Yes    Diesel             2   100734        4.0
56        Jeep              Yes    Petrol     2.0 Turbo     5323        4.0
73        Jeep              Yes    Diesel             2    84506        4.0
...        ...              ...       ...           ...      ...        ...
19144    Sedan              Yes    Petrol             2    67365        4.0
19161     Jeep              Yes    Hybrid           3.5    97000        6.0
19180    Sedan              Yes       LPG             2     5305        4.0
19188     Jeep               No    Hybrid           2.5    71234        4.0
19211     Jeep              Yes    Diesel             2   121902        4.0

      Gear box type Drive wheels   Doors       Wheel   Color  Airbags
14        Automatic        Front  04-May  Left wheel   White        4
36        Tiptronic        Front  04-May  Left wheel     Red       12
47        Automatic        Front  04-May  Left wheel   Black        4
56        Tiptronic          4x4  04-May  Left wheel    Grey        0
73        Automatic        Front  04-May  Left wheel  Silver        4
...             ...          ...     ...         ...     ...      ...
19144     Automatic        Front  04-May  Left wheel   Black        4
19161      Variator          4x4  04-May  Left wheel   Black       12
19180     Automatic        Front  04-May  Left wheel  Silver        4
19188     Tiptronic          4x4  04-May  Left wheel   White       12
19211     Automatic        Front  04-May  Left wheel   Black        4

[1073 rows x 18 columns]
number of outliers for Price: 1073
=================
Outliers less than minimum: Empty DataFrame
Columns: [ID, Price, Levy, Manufacturer, Model, Prod. year, Category, Leather interior, Fuel type, Engine volume, Mileage, Cylinders, Gear box type, Drive wheels, Doors, Wheel, Color, Airbags]
Index: []
Outliers more than maximum:              ID  Price   Levy   Manufacturer      Model  Prod. year Category  \
18     45772104    549   2386        HYUNDAI     Sonata        2006    Sedan
26     45759112    549   2455          LEXUS     GX 470        2008     Jeep
78     45759890    862   2455          LEXUS     GX 470        2008     Jeep
115    45534351  11917  11714  MERCEDES-BENZ  E 500 AMG        2003    Sedan
132    45767013    549   2866         NISSAN     Maxima        2004    Sedan
...         ...    ...    ...            ...        ...         ...      ...
18854  45769818    282   2455          LEXUS     GX 470        2008     Jeep
18957  44674964  14740  11706  MERCEDES-BENZ  E 500 AVG        2005    Sedan
18963  45780821     33   2308         HUMMER         H3        2007     Jeep
18984  45221191  11917  11714  MERCEDES-BENZ      E 500        2003    Sedan
19048  45770541  14113   4860  MERCEDES-BENZ     CL 600        2002    Coupe

      Leather interior Fuel type Engine volume  Mileage  Cylinders  \
18                 Yes    Petrol           3.3   295059        6.0
26                 Yes    Petrol           4.7        0        8.0
78                 Yes    Petrol           4.7   263190        8.0
115                Yes    Petrol             5   150000       12.0
132                Yes    Petrol           3.5   299709        6.0
...                ...       ...           ...      ...        ...
18854              Yes    Petrol           4.7   218126        8.0
18957              Yes    Petrol             5    56000       12.0
18963               No    Petrol     3.7 Turbo   185000        5.0
18984              Yes    Petrol             5   150000       12.0
19048              Yes    Petrol             6   127000       12.0

      Gear box type Drive wheels   Doors             Wheel   Color  Airbags
18        Automatic         Rear  04-May        Left wheel    Blue       12
26        Automatic          4x4  04-May        Left wheel   White        0
78        Automatic          4x4  04-May        Left wheel   White        0
115       Tiptronic         Rear  04-May  Right-hand drive   White       12
132       Automatic        Front  04-May        Left wheel    Grey       12
...             ...          ...     ...               ...     ...      ...
18854     Automatic          4x4  04-May        Left wheel   Black        0
18957     Tiptronic         Rear  04-May  Right-hand drive   Black       12
18963     Tiptronic          4x4  04-May        Left wheel   Beige       12
18984     Tiptronic         Rear  04-May  Right-hand drive   White       12
19048     Tiptronic         Rear  02-Mar        Left wheel  Silver       12

[161 rows x 18 columns]
number of outliers for Levy: 161
=================
Outliers less than minimum:              ID  Price  Levy   Manufacturer      Model  Prod. year  \
11     45814819   8781     0           FORD    Transit        1999
12     45815568   3000     0           OPEL     Vectra        1997
24     45813492   4704     0           OPEL     Vectra        1995
83     45765301   8154     0          HONDA       Cr-v        1998
91     45733554   2822     0            BMW  520 Vanos        1995
...         ...    ...   ...            ...        ...         ...
19187  45772786   7213     0            BMW        525        1998
19193  45793905   7527     0     MITSUBISHI  Pajero IO        1999
19194  45715218    500     0           FORD    Transit        1998
19199  45761409   3763     0  MERCEDES-BENZ      C 180        1995
19232  45798355   8467     0  MERCEDES-BENZ    CLK 200        1999

          Category Leather interior Fuel type Engine volume     Mileage  \
11        Microbus               No       CNG             4           0
12     Goods wagon               No       CNG           1.6      350000
24           Sedan               No    Petrol           1.8           0
83            Jeep               No    Petrol             2           0
91           Sedan              Yes    Petrol             2      350000
...            ...              ...       ...           ...         ...
19187        Sedan               No       CNG           2.5      212000
19193         Jeep               No    Petrol           1.8      245000
19194     Microbus               No    Diesel           2.5      760000
19199        Sedan               No    Petrol           1.8  1111111111
19232        Coupe              Yes       CNG     2.0 Turbo      300000

       Cylinders Gear box type Drive wheels   Doors             Wheel   Color  \
11           8.0        Manual         Rear  02-Mar        Left wheel    Blue
12           4.0        Manual        Front  04-May        Left wheel   White
24           4.0     Automatic        Front  04-May        Left wheel   Green
83           4.0     Automatic          4x4  04-May  Right-hand drive   White
91           6.0        Manual         Rear  04-May        Left wheel    Blue
...          ...           ...          ...     ...               ...     ...
19187        6.0        Manual         Rear  04-May        Left wheel  Silver
19193        4.0     Automatic          4x4  04-May        Left wheel   Green
19194        4.0        Manual         Rear  04-May        Left wheel   White
19199        5.0        Manual         Rear  04-May  Right-hand drive   Green
19232        4.0        Manual         Rear  02-Mar        Left wheel  Silver

       Airbags
11           0
12           4
24           4
83           2
91           2
...        ...
19187        6
19193        6
19194        2
19199        2
19232        5

[982 rows x 18 columns]
Outliers more than maximum: Empty DataFrame
Columns: [ID, Price, Levy, Manufacturer, Model, Prod. year, Category, Leather interior, Fuel type, Engine volume, Mileage, Cylinders, Gear box type, Drive wheels, Doors, Wheel, Color, Airbags]
Index: []
number of outliers for Prod. year: 982
=================
Outliers less than minimum: Empty DataFrame
Columns: [ID, Price, Levy, Manufacturer, Model, Prod. year, Category, Leather interior, Fuel type, Engine volume, Mileage, Cylinders, Gear box type, Drive wheels, Doors, Wheel, Color, Airbags]
Index: []
Outliers more than maximum:              ID  Price  Levy   Manufacturer       Model  Prod. year  Category  \
8      45641395   1098   394         TOYOTA       Camry        2014     Sedan
29     45768550  12074  1537         TOYOTA  Highlander        2009      Jeep
39     45661296    314  1399          LEXUS      RX 450        2010      Jeep
65     45803550   9722   765        HYUNDAI      Sonata        2015     Sedan
90     45807330  77775  1604  MERCEDES-BENZ   GL 63 AMG        2014      Jeep
...         ...    ...   ...            ...         ...         ...       ...
19163  45771877   5018   645         TOYOTA       Prius        2011      Jeep
19167  45799423  18817  1995           FORD     Transit        2003  Microbus
19194  45715218    500     0           FORD     Transit        1998  Microbus
19199  45761409   3763     0  MERCEDES-BENZ       C 180        1995     Sedan
19222  45732720  10036   639        HYUNDAI      Sonata        2014     Sedan

      Leather interior Fuel type Engine volume     Mileage  Cylinders  \
8                  Yes    Hybrid           2.5      398069        4.0
29                 Yes    Hybrid           3.3      420550        6.0
39                 Yes    Hybrid           3.5      382746        6.0
65                 Yes       LPG             2      719847        4.0
90                 Yes    Petrol           5.5      433811        8.0
...                ...       ...           ...         ...        ...
19163              Yes    Hybrid           1.8      489584        4.0
19167               No    Diesel     2.4 Turbo  2147483647        4.0
19194               No    Diesel           2.5      760000        4.0
19199               No    Petrol           1.8  1111111111        5.0
19222              Yes       LPG             2      735970        4.0

      Gear box type Drive wheels   Doors             Wheel   Color  Airbags
8         Automatic        Front  04-May        Left wheel   Black       12
29        Automatic          4x4  04-May        Left wheel    Blue       12
39        Automatic          4x4  04-May        Left wheel  Silver       12
65        Automatic        Front  04-May        Left wheel  Orange        4
90        Automatic          4x4  04-May        Left wheel   Black       10
...             ...          ...     ...               ...     ...      ...
19163     Automatic        Front  04-May        Left wheel    Grey       12
19167        Manual        Front  02-Mar        Left wheel   White        2
19194        Manual         Rear  04-May        Left wheel   White        2
19199        Manual         Rear  04-May  Right-hand drive   Green        2
19222     Automatic        Front  04-May        Left wheel  Silver        4

[640 rows x 18 columns]
number of outliers for Mileage: 640
=================
Outliers less than minimum:              ID   Price  Levy   Manufacturer         Model  Prod. year  \
54     44153312   38500   639           AUDI            Q5        2014
121    45787329    3450     0        RENAULT          Clio        1995
171    45782173    1300     0           AUDI            50        2018
380    44719048    5645   706     MITSUBISHI             I        2011
394    45759758    4391     0     MITSUBISHI   Pajero Mini        2006
...         ...     ...   ...            ...           ...         ...
18810  45786558   10036   494     MITSUBISHI        Mirage        2015
18835  45816091    6400     0       DAIHATSU          Mira        2012
18881  44587551  147397     0         JAGUAR        F-pace        2017
19092  44563390   29793     0  MERCEDES-BENZ         Smart        2016
19183  45783805   11917  1268         TOYOTA  Prius C aqua        2012

        Category Leather interior Fuel type Engine volume  Mileage  Cylinders  \
54          Jeep              Yes    Petrol             2    87000        1.0
121    Hatchback               No    Petrol           1.2    50000        3.0
171        Coupe              Yes    Petrol           0.5     4000        1.0
380    Hatchback               No    Petrol           0.7    92000        3.0
394         Jeep               No    Petrol           0.7   314000        3.0
...          ...              ...       ...           ...      ...        ...
18810  Hatchback               No    Petrol           1.2    80000        3.0
18835  Hatchback               No    Petrol           0.7   103000        3.0
18881       Jeep               No    Diesel             2    17060        1.0
19092      Coupe               No    Petrol     1.0 Turbo    37000        3.0
19183  Hatchback               No    Hybrid           1.5   157000        3.0

      Gear box type Drive wheels   Doors             Wheel   Color  Airbags
54        Tiptronic          4x4  04-May        Left wheel   White       12
121          Manual        Front  02-Mar        Left wheel   Green        0
171       Tiptronic         Rear      >5  Right-hand drive    Blue        0
380       Automatic        Front  04-May  Right-hand drive   Brown        2
394          Manual          4x4  02-Mar  Right-hand drive  Silver        2
...             ...          ...     ...               ...     ...      ...
18810     Tiptronic        Front  04-May        Left wheel    Blue       16
18835      Variator        Front  04-May  Right-hand drive   Black        2
18881     Automatic          4x4  04-May        Left wheel    Grey        0
19092     Tiptronic         Rear  04-May        Left wheel   White        8
19183     Automatic        Front  04-May  Right-hand drive  Silver        8

[187 rows x 18 columns]
Outliers more than maximum:              ID  Price  Levy   Manufacturer    Model  Prod. year  Category  \
0      45654403  13328  1399          LEXUS   RX 450        2010      Jeep
1      44731507  16621  1018      CHEVROLET  Equinox        2011      Jeep
9      45756839  26657     0          LEXUS   RX 350        2007      Jeep
10     45621750    941  1053  MERCEDES-BENZ    E 350        2014     Sedan
11     45814819   8781     0           FORD  Transit        1999  Microbus
...         ...    ...   ...            ...      ...         ...       ...
19221  45776906  15681     0     VOLKSWAGEN    Jetta        2013     Sedan
19226  45796788   7840     0         NISSAN  Skyline        2003     Sedan
19227  45769427  29793  1053  MERCEDES-BENZ    E 350        2014     Sedan
19228  45773726    706  1850  MERCEDES-BENZ    E 350        2008     Sedan
19231  45772306   5802  1055  MERCEDES-BENZ    E 350        2013     Sedan

      Leather interior Fuel type Engine volume  Mileage  Cylinders  \
0                  Yes    Hybrid           3.5   186005        6.0
1                   No    Petrol             3   192000        6.0
9                  Yes    Petrol           3.5   128500        6.0
10                 Yes    Diesel           3.5   184467        6.0
11                  No       CNG             4        0        8.0
...                ...       ...           ...      ...        ...
19221              Yes    Petrol           2.5    81200        5.0
19226              Yes    Petrol             3   220000        6.0
19227              Yes    Diesel           3.5   219030        6.0
19228              Yes    Diesel           3.5   122874        6.0
19231              Yes    Diesel           3.5   107800        6.0

      Gear box type Drive wheels   Doors             Wheel   Color  Airbags

                 lower       upper  outlier_count  outlier_pct
ID          45542881.0  45957529.0         2531.0        13.16
Price         -19785.0     47191.0         1073.0         5.58
Levy           -1375.5      2292.5          161.0         0.84
Prod. year      2000.0      2024.0          982.0         5.10
Mileage      -107984.5    367011.5          640.0         3.33
Cylinders          4.0         4.0         4870.0        25.32
Airbags           -8.0        24.0            0.0         0.00

In [10]:
def handle_outlier(df,col,outlier_percent,mini,maxi):
    lower_index = list(df[df[col]<mini].index) # contains index of all such values which are below min
    upper_index = list(df[df[col]>maxi].index) # contains index of all such values which are above max
    all_ = lower_index + upper_index
    # Perform outlier handling on basis of percentage of outliers present in the data
    df_new = df.copy()
    if outlier_percent<10:
        df_new = df.drop(index=all_) # drops on basis of index we have provided
    else:
        df_new[col] = df[col].clip(mini,maxi)
    return df_new

In [11]:
df2 = df.copy()
for i in con:
    # df.loc[row_name,column_name]
    out_perc = out_report.loc[i,'outlier_pct']
    mini = out_report.loc[i,'lower']
    maxi = out_report.loc[i,'upper']
    df2 = handle_outlier(df2,i,out_perc,mini,maxi=maxi) # positional arguments,keyword arguments
df2

,ID,Price,Levy,Manufacturer,Model,Prod. year,Category,Leather interior,Fuel type,Engine volume,Mileage,Cylinders,Gear box type,Drive wheels,Doors,Wheel,Color,Airbags
0,45654403,13328,1399,LEXUS,RX 450,2010,Jeep,Yes,Hybrid,3.5,186005,4.0,Automatic,4x4,04-May,Left wheel,Silver,12
1,45542881,16621,1018,CHEVROLET,Equinox,2011,Jeep,No,Petrol,3,192000,4.0,Tiptronic,4x4,04-May,Left wheel,Black,8
2,45774419,8467,0,HONDA,FIT,2006,Hatchback,No,Petrol,1.3,200000,4.0,Variator,Front,04-May,Right-hand drive,Black,2
3,45769185,3607,862,FORD,Escape,2011,Jeep,Yes,Hybrid,2.5,168966,4.0,Automatic,4x4,04-May,Left wheel,White,0
4,45809263,11726,446,HONDA,FIT,2014,Hatchback,Yes,Petrol,1.3,91901,4.0,Automatic,Front,04-May,Left wheel,Silver,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19231,45772306,5802,1055,MERCEDES-BENZ,E 350,2013,Sedan,Yes,Diesel,3.5,107800,4.0,Automatic,Rear,04-May,Left wheel,Grey,12
19233,45778856,15681,831,HYUNDAI,Sonata,2011,Sedan,Yes,Petrol,2.4,161600,4.0,Tiptronic,Front,04-May,Left wheel,Red,8
19234,45804997,26108,836,HYUNDAI,Tucson,2010,Jeep,Yes,Diesel,2,116365,4.0,Automatic,Front,04-May,Left wheel,Grey,4
19235,45793526,5331,1288,CHEVROLET,Captiva,2007,Jeep,Yes,Diesel,2,51258,4.0,Automatic,Front,04-May,Left wheel,Black,4
19236,45813273,470,753,HYUNDAI,Sonata,2012,Sedan,Yes,Hybrid,2.4,186923,4.0,Automatic,Front,04-May,Left wheel,White,12

## separate x and y

In [12]:
X = df2.drop(columns=['ID',"Price","Gear box type","Drive wheels","Doors","Wheel"])
Y = df2[['Price']]

In [13]:
for i in ['Manufacturer','Model','Category','Leather interior','Fuel type','Engine volume','Color']:
    print(i,X[i].unique(),sep='\n')

Manufacturer
['LEXUS' 'CHEVROLET' 'HONDA' 'FORD' 'HYUNDAI' 'TOYOTA' 'MERCEDES-BENZ'
 'PORSCHE' 'BMW' 'JEEP' 'VOLKSWAGEN' 'AUDI' 'RENAULT' 'NISSAN' 'SUBARU'
 'DAEWOO' 'KIA' 'MITSUBISHI' 'SSANGYONG' 'MAZDA' 'GMC' 'FIAT' 'INFINITI'
 'ALFA ROMEO' 'SUZUKI' 'OPEL' 'ACURA' 'CITROEN' 'MINI' 'DODGE' 'CHRYSLER'
 'ISUZU' 'VAZ' 'JAGUAR' 'SKODA' 'LINCOLN' 'BUICK' 'DAIHATSU' 'CADILLAC'
 'PEUGEOT' 'VOLVO' 'სხვა' 'HAVAL' 'LAND ROVER' 'SCION' 'MERCURY' 'SEAT'
 'LANCIA' 'MASERATI' 'HUMMER' 'SAAB' 'GAZ' 'UAZ' 'PONTIAC' 'SATURN'
 'GREATWALL']
Model
['RX 450' 'Equinox' 'FIT' ... '406' 'Prius C aqua' 'Optima ex']
Category
['Jeep' 'Hatchback' 'Sedan' 'Microbus' 'Goods wagon' 'Universal' 'Coupe'
 'Minivan' 'Cabriolet' 'Pickup' 'Limousine']
Leather interior
['Yes' 'No']
Fuel type
['Hybrid' 'Petrol' 'Diesel' 'Plug-in Hybrid' 'CNG' 'LPG' 'Hydrogen']
Engine volume
['3.5' '3' '1.3' '2.5' '2' '1.8' '2.4' '1.6' '2.0 Turbo' '2.2 Turbo' '1.5'
 '4.4' '3.3' '3.0 Turbo' '1.4 Turbo' '3.6' '4' '2.3' '1.5 Turbo'
 '1.6 Turbo' '2.2' '2.3 Turbo' '1.4' '3.2' '3.8' '4.6' '1.2' '1.7' '2.9'
 '0.5' '1.8 Turbo' '2.4 Turbo' '1.9' '5.5' '5.3' '0.4' '2.8' '5' '2.1'
 '0.7' '4.8' '1.3 Turbo' '2.7' '4.7' '3.7' '1' '2.6' '0.8' '0.2 Turbo'
 '2.5 Turbo' '3.5 Turbo' '4.8 Turbo' '1.2 Turbo' '3.4' '1.7 Turbo'
 '4.6 Turbo' '5.7' '2.8 Turbo' '2.7 Turbo' '4.2' '2.9 Turbo' '1.9 Turbo'
 '4.4 Turbo' '1.1' '3.7 Turbo' '0' '0.2' '2.1 Turbo' '6.2' '0.7 Turbo'
 '0.6 Turbo' '4.5' '5.5 Turbo' '3.2 Turbo' '0.6' '3.6 Turbo' '0.1'
 '1.0 Turbo' '4.7 Turbo' '4.5 Turbo' '0.8 Turbo' '4.3' '3.9' '4.2 Turbo'
 '5.9' '6.3' '6' '5.0 Turbo' '5.4 Turbo' '0.3 Turbo' '5.8' '5.6']
Color
['Silver' 'Black' 'White' 'Grey' 'Blue' 'Sky blue' 'Red' 'Green' 'Yellow'
 'Brown' 'Golden' 'Beige' 'Orange' 'Carnelian red' 'Purple' 'Pink']

**Manufacturer and Engine volume has too many unique features. will apply Label encoding to it**

In [14]:
cat = list(X.select_dtypes(include='object').columns) 
con = list(X.select_dtypes(include='number').columns)
print(cat)
print(con)

['Manufacturer', 'Model', 'Category', 'Leather interior', 'Fuel type', 'Engine volume', 'Color']
['Levy', 'Prod. year', 'Mileage', 'Cylinders', 'Airbags']

In [15]:
cat_onehot = ['Model', 'Category', 'Leather interior', 'Fuel type', 'Color']
cat_label = ['Manufacturer','Engine volume']

In [16]:
from sklearn.pipeline import make_pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler,OneHotEncoder,LabelEncoder
from sklearn.compose import ColumnTransformer

num_pipe = make_pipeline(SimpleImputer(strategy='median'),
                         StandardScaler())

cat_pipe = make_pipeline(SimpleImputer(strategy='most_frequent'),
                         OneHotEncoder(handle_unknown='ignore',sparse_output=False))

pre = ColumnTransformer([('cat',cat_pipe,cat_onehot),
                         ('con',num_pipe,con)]).set_output(transform='pandas')

from sklearn.model_selection import train_test_split
xtrain,xtest,ytrain,ytest = train_test_split(X,Y,random_state=21,train_size=0.75)

pre.fit(xtrain)

xtrain_pre = pre.transform(xtrain)
xtest_pre = pre.transform(xtest)

# Apply LabelEncoder separately
encoders = {}

for col in cat_label:
    # Impute missing values using training data's most frequent value
    most_frequent = xtrain[col].mode().iloc[0]

    train_col = xtrain[col].fillna(most_frequent).astype(str)
    test_col = xtest[col].fillna(most_frequent).astype(str)

    le = LabelEncoder()
    xtrain_pre[col] = le.fit_transform(train_col)

    # Handle categories in test data that weren't present in training
    mapping = {v: i for i, v in enumerate(le.classes_)}
    xtest_pre[col] = test_col.map(mapping).fillna(-1).astype(int)

    encoders[col] = le

In [33]:
xtrain_pre.columns

Index(['cat__Model_09-Mar', 'cat__Model_100', 'cat__Model_100 NX',
       'cat__Model_1000', 'cat__Model_114', 'cat__Model_116', 'cat__Model_118',
       'cat__Model_128', 'cat__Model_128 M tech', 'cat__Model_130',
       ...
       'cat__Color_Sky blue', 'cat__Color_White', 'cat__Color_Yellow',
       'con__Levy', 'con__Prod. year', 'con__Mileage', 'con__Cylinders',
       'con__Airbags', 'Manufacturer', 'Engine volume'],
      dtype='object', length=1180)

## Algorithm Evaluation

In [17]:
import re

# Replace [, ], and < with an underscore
xtrain_pre.columns = [re.sub(r'[\[\]<]', '_', str(col)) for col in xtrain_pre.columns]
xtest_pre.columns = [re.sub(r'[\[\]<]', '_', str(col)) for col in xtest_pre.columns]

In [18]:
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor,GradientBoostingRegressor

In [19]:
pip install xgboost

Requirement already satisfied: xgboost in c:\users\hp\anaconda3\lib\site-packages (3.4.1)
Requirement already satisfied: numpy in c:\users\hp\anaconda3\lib\site-packages (from xgboost) (2.1.3)
Requirement already satisfied: scipy in c:\users\hp\anaconda3\lib\site-packages (from xgboost) (1.15.3)
Note: you may need to restart the kernel to use updated packages.

In [20]:
from xgboost import XGBRegressor

In [21]:
dct = {
    "Linear":LinearRegression(),
    "Decision":DecisionTreeRegressor(),
    "Random":RandomForestRegressor(),
    "Gradient":GradientBoostingRegressor(),
    "XGB":XGBRegressor()
}

In [22]:
r2 = []
from sklearn.metrics import r2_score
for model in dct.values():
    model.fit(xtrain_pre,ytrain['Price'])
    preds = model.predict(xtest_pre)
    score = r2_score(ytest,preds)
    r2.append(score)

In [23]:
r2

[0.3897110904655585,
 0.600043384165748,
 0.7498815527322871,
 0.5782403136332779,
 0.6993575096130371]

In [24]:
model_results = pd.DataFrame(list(zip(list(dct.keys()),r2)),columns=["Model Name","R2 Scores"]).sort_values(by="R2 Scores",ascending=False)
model_results

  Model Name  R2 Scores
2     Random   0.749882
4        XGB   0.699358
1   Decision   0.600043
3   Gradient   0.578240
0     Linear   0.389711

In [29]:
params ={'n_estimators':[50,100,125,150],
        'max_depth':[10,15,20,25]}

In [30]:
from sklearn.model_selection import RandomizedSearchCV
rscv = RandomizedSearchCV(estimator=RandomForestRegressor(),param_distributions=params,cv=3,scoring='r2')
rscv.fit(xtrain_pre,ytrain['Price'])

RandomizedSearchCV(cv=3, estimator=RandomForestRegressor(),
                   param_distributions={'max_depth': [10, 15, 20, 25],
                                        'n_estimators': [50, 100, 125, 150]},
                   scoring='r2')

In [31]:
rscv.best_params_

{'n_estimators': 125, 'max_depth': 25}

In [32]:
rscv.best_score_

np.float64(0.705659361756362)