<a href="https://colab.research.google.com/github/sindhura-nk/Machine-Learning-1663/blob/main/PCA_Principal_Component_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Principal Component Analysis -> A technique used to eliminate curse of Dimensionality

In [3]:
import pandas as pd
df = pd.read_csv(r"https://raw.githubusercontent.com/sindhura-nk/Datasets/refs/heads/main/Cars93.csv",na_values=['NA',''],keep_default_na=False)
df.head()

,id,Manufacturer,Model,Type,Min.Price,Price,Max.Price,MPG.city,MPG.highway,AirBags,...,Passengers,Length,Wheelbase,Width,Turn.circle,Rear.seat.room,Luggage.room,Weight,Origin,Make
0,1,Acura,Integra,Small,12.9,15.9,18.8,25,31,None,...,5,177,102,68,37,26.5,11.0,2705,non-USA,Acura Integra
1,2,Acura,Legend,Midsize,29.2,33.9,38.7,18,25,Driver & Passenger,...,5,195,115,71,38,30.0,15.0,3560,non-USA,Acura Legend
2,3,Audi,90,Compact,25.9,29.1,32.3,20,26,Driver only,...,5,180,102,67,37,28.0,14.0,3375,non-USA,Audi 90
3,4,Audi,100,Midsize,30.8,37.7,44.6,19,26,NaN,...,6,193,106,70,37,31.0,17.0,3405,non-USA,Audi 100
4,5,BMW,535i,Midsize,23.7,30.0,36.2,22,30,Driver only,...,4,186,109,69,39,27.0,13.0,3640,non-USA,BMW 535i

## Perform basic data quality checks

In [4]:
df.shape

(93, 28)

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 93 entries, 0 to 92
Data columns (total 28 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   id                  93 non-null     int64
 1   Manufacturer        93 non-null     object
 2   Model               93 non-null     object
 3   Type                93 non-null     object
 4   Min.Price           93 non-null     float64
 5   Price               93 non-null     float64
 6   Max.Price           93 non-null     float64
 7   MPG.city            93 non-null     int64
 8   MPG.highway         93 non-null     int64
 9   AirBags             89 non-null     object
 10  DriveTrain          93 non-null     object
 11  Cylinders           93 non-null     object
 12  EngineSize          93 non-null     float64
 13  Horsepower          93 non-null     int64
 14  RPM                 93 non-null     int64
 15  Rev.per.mile        93 non-null     int64
 16  Man.trans.avail     93 non-null     object
 17  Fuel.tank.capacity  93 non-null     float64
 18  Passengers          93 non-null     int64
 19  Length              93 non-null     int64
 20  Wheelbase           93 non-null     int64
 21  Width               93 non-null     int64
 22  Turn.circle         93 non-null     int64
 23  Rear.seat.room      91 non-null     float64
 24  Luggage.room        82 non-null     float64
 25  Weight              93 non-null     int64
 26  Origin              93 non-null     object
 27  Make                93 non-null     object
dtypes: float64(7), int64(12), object(9)
memory usage: 20.5+ KB

In [6]:
df.duplicated().sum()

np.int64(0)

In [7]:
df.isna().sum()

id                     0
Manufacturer           0
Model                  0
Type                   0
Min.Price              0
Price                  0
Max.Price              0
MPG.city               0
MPG.highway            0
AirBags                4
DriveTrain             0
Cylinders              0
EngineSize             0
Horsepower             0
RPM                    0
Rev.per.mile           0
Man.trans.avail        0
Fuel.tank.capacity     0
Passengers             0
Length                 0
Wheelbase              0
Width                  0
Turn.circle            0
Rear.seat.room         2
Luggage.room          11
Weight                 0
Origin                 0
Make                   0
dtype: int64

## Separate X and Y features

In [8]:
X = df.drop(columns=['id','Weight'])
Y = df[['Weight']]

In [9]:
X.head()

,Manufacturer,Model,Type,Min.Price,Price,Max.Price,MPG.city,MPG.highway,AirBags,DriveTrain,...,Fuel.tank.capacity,Passengers,Length,Wheelbase,Width,Turn.circle,Rear.seat.room,Luggage.room,Origin,Make
0,Acura,Integra,Small,12.9,15.9,18.8,25,31,None,Front,...,13.2,5,177,102,68,37,26.5,11.0,non-USA,Acura Integra
1,Acura,Legend,Midsize,29.2,33.9,38.7,18,25,Driver & Passenger,Front,...,18.0,5,195,115,71,38,30.0,15.0,non-USA,Acura Legend
2,Audi,90,Compact,25.9,29.1,32.3,20,26,Driver only,Front,...,16.9,5,180,102,67,37,28.0,14.0,non-USA,Audi 90
3,Audi,100,Midsize,30.8,37.7,44.6,19,26,NaN,Front,...,21.1,6,193,106,70,37,31.0,17.0,non-USA,Audi 100
4,BMW,535i,Midsize,23.7,30.0,36.2,22,30,Driver only,Rear,...,21.1,4,186,109,69,39,27.0,13.0,non-USA,BMW 535i

In [10]:
Y.head()

   Weight
0    2705
1    3560
2    3375
3    3405
4    3640

In [11]:
from sklearn.model_selection import train_test_split
xtrain,xtest,ytrain,ytest = train_test_split(X,Y,random_state=21,train_size=0.85)

## Data preprocessing and Data cleaning

In [15]:
from sklearn.pipeline import make_pipeline
from sklearn.impute import SimpleImputer
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import StandardScaler,OneHotEncoder

cat = list(X.select_dtypes(include='object'))
con = list(X.select_dtypes(include='number'))

num_pipe = make_pipeline(SimpleImputer(strategy='median'),StandardScaler())

cat_pipe = make_pipeline(SimpleImputer(strategy='most_frequent'),OneHotEncoder(handle_unknown='ignore',sparse_output=False))

pre = ColumnTransformer([
    ('cat',cat_pipe,cat),
    ('con',num_pipe,con)
]).set_output(transform='pandas')
pre

ColumnTransformer(transformers=[('cat',
                                 Pipeline(steps=[('simpleimputer',
                                                  SimpleImputer(strategy='most_frequent')),
                                                 ('onehotencoder',
                                                  OneHotEncoder(handle_unknown='ignore',
                                                                sparse_output=False))]),
                                 ['Manufacturer', 'Model', 'Type', 'AirBags',
                                  'DriveTrain', 'Cylinders', 'Man.trans.avail',
                                  'Origin', 'Make']),
                                ('con',
                                 Pipeline(steps=[('simpleimputer',
                                                  SimpleImputer(strategy='median')),
                                                 ('standardscaler',
                                                  StandardScaler())]),
                                 ['Min.Price', 'Price', 'Max.Price', 'MPG.city',
                                  'MPG.highway', 'EngineSize', 'Horsepower',
                                  'RPM', 'Rev.per.mile', 'Fuel.tank.capacity',
                                  'Passengers', 'Length', 'Wheelbase', 'Width',
                                  'Turn.circle', 'Rear.seat.room',
                                  'Luggage.room'])])

In [16]:
pre.fit(xtrain)

ColumnTransformer(transformers=[('cat',
                                 Pipeline(steps=[('simpleimputer',
                                                  SimpleImputer(strategy='most_frequent')),
                                                 ('onehotencoder',
                                                  OneHotEncoder(handle_unknown='ignore',
                                                                sparse_output=False))]),
                                 ['Manufacturer', 'Model', 'Type', 'AirBags',
                                  'DriveTrain', 'Cylinders', 'Man.trans.avail',
                                  'Origin', 'Make']),
                                ('con',
                                 Pipeline(steps=[('simpleimputer',
                                                  SimpleImputer(strategy='median')),
                                                 ('standardscaler',
                                                  StandardScaler())]),
                                 ['Min.Price', 'Price', 'Max.Price', 'MPG.city',
                                  'MPG.highway', 'EngineSize', 'Horsepower',
                                  'RPM', 'Rev.per.mile', 'Fuel.tank.capacity',
                                  'Passengers', 'Length', 'Wheelbase', 'Width',
                                  'Turn.circle', 'Rear.seat.room',
                                  'Luggage.room'])])

In [17]:
xtrain_pre = pre.transform(xtrain)
xtest_pre = pre.transform(xtest)

In [25]:
xtrain_pre.shape[1]

228

## PCA components

In [18]:
from sklearn.decomposition import PCA
pca = PCA(n_components=3)
pca.fit(xtrain_pre)

PCA(n_components=3)

In [19]:
xtrain_pca = pca.transform(xtrain_pre)
xtrain_pca

array([[-4.27587365e+00, -4.62566329e-01,  8.56519492e-01],
       [-1.64632376e+00,  1.18179499e+00, -1.13334982e+00],
       [ 2.71009092e+00, -1.46768142e+00,  2.68470722e-01],
       [ 1.65667530e+00, -7.82448693e-01, -1.33952286e+00],
       [-4.95911869e+00, -2.31324001e-01, -3.14206609e-01],
       [-3.01470569e-01,  2.41438244e+00,  2.64517501e-01],
       [-2.72840658e+00, -2.70957018e-01,  8.04907069e-01],
       [ 2.29152874e+00,  1.54962039e+00,  7.09345465e-01],
       [ 2.89173638e+00, -6.61830667e-01,  3.27561579e-01],
       [ 6.78740631e+00, -6.76026508e-02, -1.26275081e+00],
       [ 1.95569542e+00,  4.15382000e+00,  7.71995627e-01],
       [ 5.47235505e+00, -1.93194965e+00, -1.83864086e+00],
       [ 6.45274636e-01, -1.68847561e+00,  5.07578979e-01],
       [-4.11802759e+00,  4.71650159e-01, -7.53377408e-01],
       [ 2.29455419e-01, -1.07635167e+00, -5.53283687e-01],
       [-2.01911480e+00, -7.38058194e-01, -6.60622383e-01],
       [-2.37839496e+00,  1.57490325e-01, -6.48562521e-01],
       [-2.99391849e-01, -1.72270532e+00,  5.96329156e-01],
       [-6.74638014e-01,  4.45333720e-02,  1.90748384e-03],
       [ 3.04892200e+00,  2.97730146e-01, -1.17776604e+00],
       [ 2.63122067e+00, -1.29352351e+00,  1.47236392e+00],
       [ 6.79589434e+00, -1.96397913e+00, -1.79257600e+00],
       [ 7.51601858e-01,  2.01465236e+00,  6.93001058e-01],
       [-9.50716638e-01,  7.43073043e-01,  3.35792007e-01],
       [-6.79125773e-01,  4.71011649e-01,  1.72044886e-01],
       [ 2.07953703e+00, -5.39166621e-01, -5.73903089e-01],
       [ 4.32563733e+00,  5.90441119e+00,  7.07912136e-01],
       [-1.26157868e+00, -1.64697430e+00, -7.82238560e-02],
       [ 2.50416901e+00, -1.22917873e+00,  1.04776522e+00],
       [-7.41016901e+00, -2.58106258e-01, -6.63834808e-01],
       [ 5.78974000e+00,  4.44224063e+00,  5.43044544e-01],
       [-2.56492416e-01, -4.09193543e-01,  1.49582457e+00],
       [-5.77289097e+00, -6.38331719e-01, -4.83885636e-01],
       [-6.06135650e-01,  3.22196063e-02,  1.80255719e-01],
       [-7.53258719e-01,  5.39758835e-01,  1.95619354e+00],
       [ 1.51417275e+00,  3.89847290e-01,  1.43239091e-01],
       [-4.50852153e+00, -5.44558434e-01,  4.08948837e-01],
       [-3.71917659e+00, -8.98989714e-01, -8.05792711e-01],
       [-8.29601376e-01, -5.59247418e-01,  2.04852259e-01],
       [-2.49808265e+00,  7.10993716e-01,  1.10640448e+00],
       [-4.51965136e+00,  7.02345512e-01, -6.22658360e-01],
       [ 5.22207854e+00, -3.17306912e+00,  1.92833827e+00],
       [ 6.03987014e+00, -4.64899141e-01, -6.76972210e-01],
       [-3.40376867e+00, -3.75682265e-01,  2.41856802e-01],
       [ 8.93919093e-01, -1.91871302e+00,  1.75545110e-01],
       [-2.34403469e+00, -1.41547727e+00, -1.45208622e+00],
       [ 3.62217926e+00, -1.48437874e+00, -7.93631240e-01],
       [ 3.21749843e+00, -2.17657822e+00,  9.36902732e-01],
       [ 1.00079261e+00,  1.73983861e+00,  1.48522860e+00],
       [ 3.72052031e+00, -1.90641404e+00,  8.43384708e-01],
       [-1.55212887e+00, -1.04014208e+00, -7.02738809e-01],
       [-1.05897999e+00,  3.15750503e-02, -1.79558128e+00],
       [-4.46825845e+00,  1.27042754e-01,  1.73498940e-01],
       [ 1.78277537e-02,  1.37325866e-01,  4.24138516e-01],
       [-2.98048973e+00, -4.27167987e-01, -7.39847726e-02],
       [-2.93345592e+00, -5.62311807e-01,  1.04267619e+00],
       [-3.58697445e-01,  2.24834614e+00,  1.31039884e+00],
       [ 4.69259373e+00, -5.97169626e-03, -4.95743256e-01],
       [ 3.69721873e+00, -1.58600939e+00, -6.38949507e-01],
       [ 4.10862823e+00,  4.19707562e+00, -3.12840278e+00],
       [ 2.24621687e-01, -1.40590459e+00, -6.41904857e-02],
       [-4.41174619e+00, -1.17021177e-01, -1.30116950e+00],
       [-4.79704002e-01,  2.31778095e+00,  7.18861736e-01],
       [ 3.55968243e+00, -1.03588954e+00, -5.59876530e-01],
       [ 6.72227017e-01, -1.42374405e+00,  1.91918227e-01],
       [-3.95997297e+00,  1.49445133e+00, -9.00447433e-01],
       [ 2.07714510e+00, -1.69953793e+00,  3.39434345e+00],
       [-3.61977827e+00, -2.46222653e-01,  5.28973468e-01],
       [-2.82553599e+00, -1.30119812e-01,  1.31992386e+00],
       [-3.62594204e+00,  3.22328716e-01,  2.51725627e-01],
       [-4.03944311e+00, -9.69874598e-01, -1.13854375e+00],
       [ 1.43069913e+00, -6.18523004e-02, -2.42354094e+00],
       [ 2.51469972e+00, -1.84608059e+00, -1.21277091e+00],
       [ 3.38080472e+00, -1.56041893e+00,  1.60907533e+00],
       [ 1.83677740e+00,  1.68212608e+00,  4.56282193e-01],
       [ 1.38333497e+00,  2.79559060e+00, -2.41936501e-02],
       [ 3.87603659e-01,  5.11451771e+00,  3.78283693e-02],
       [-6.57559963e+00,  5.96807401e-01, -3.81189229e-01],
       [-1.97813808e+00, -9.09700908e-01, -1.80706367e-01]])

In [21]:
pca.explained_variance_

array([10.96924237,  2.97505309,  1.13701709])

In [23]:
len(pca.feature_names_in_)

228

## Converting  array into dataframe

In [26]:
X_pca = pd.DataFrame(xtrain_pca)
X_pca

           0         1         2
0  -4.275874 -0.462566  0.856519
1  -1.646324  1.181795 -1.133350
2   2.710091 -1.467681  0.268471
3   1.656675 -0.782449 -1.339523
4  -4.959119 -0.231324 -0.314207
..       ...       ...       ...
74  1.836777  1.682126  0.456282
75  1.383335  2.795591 -0.024194
76  0.387604  5.114518  0.037828
77 -6.575600  0.596807 -0.381189
78 -1.978138 -0.909701 -0.180706

[79 rows x 3 columns]

In [27]:
X_pca.columns = ['PC1','PC2','PC3']
X_pca

         PC1       PC2       PC3
0  -4.275874 -0.462566  0.856519
1  -1.646324  1.181795 -1.133350
2   2.710091 -1.467681  0.268471
3   1.656675 -0.782449 -1.339523
4  -4.959119 -0.231324 -0.314207
..       ...       ...       ...
74  1.836777  1.682126  0.456282
75  1.383335  2.795591 -0.024194
76  0.387604  5.114518  0.037828
77 -6.575600  0.596807 -0.381189
78 -1.978138 -0.909701 -0.180706

[79 rows x 3 columns]

In [29]:
from sklearn.ensemble import RandomForestRegressor
model = RandomForestRegressor(n_estimators=50,
                              max_depth=5)
model.fit(X_pca,ytrain['Weight'])

RandomForestRegressor(max_depth=5, n_estimators=50)

In [30]:
model.score(X_pca,ytrain)

0.9874302031870712

In [32]:
Xtest_pca = pca.transform(xtest_pre)
Xtest_pca

array([[-2.07476485, -1.05506881, -0.49122337],
       [ 2.43320173, -0.94429478,  2.70670641],
       [ 0.02851151,  0.76023145,  0.42646395],
       [ 3.91823897, -0.88729398,  0.14181696],
       [ 5.51545749, -2.13008624, -1.53320249],
       [-6.27805521,  0.03751186, -0.1606953 ],
       [-1.2098807 , -0.08568927, -1.53446175],
       [ 1.11063929,  3.37339731, -0.99052806],
       [ 5.43305481,  2.76751913,  0.19256509],
       [-1.84967484,  1.91419052, -0.13209261],
       [ 1.15532966, -0.30314682, -2.2949644 ],
       [ 2.82326212,  2.09994399,  1.66934172],
       [ 2.07661215, -0.92456774,  1.62931811],
       [ 2.92089297,  2.02514339,  1.13704591]])

In [34]:
Xtest_pca = pd.DataFrame(Xtest_pca)
Xtest_pca.columns = ['PC1','PC2','PC3']

In [35]:
model.score(Xtest_pca,ytest)

0.8682260418032833